<?php
$page_title = "Privacy Policy | Sprouse Websites";
$url = "privacy.php";
include 'includes/header.php';
?>

<style type="text/css">
.main-text {
	padding: 5pt;
	text-align: center;
}
h1,h2,h3,h4,h5,h6 {
	font-weight: bold;
}
</style>

<script type="text/javascript">
function full() {
	document.getElementById("full-policy").style.display = "block";
	document.getElementById("summary").style.display = "none";
	document.getElementById("full-button").style.display = "none";
	document.getElementById("short-button").style.display = "block";
}

function summary() {
	document.getElementById("full-policy").style.display = "none";
	document.getElementById("summary").style.display = "block";
	document.getElementById("full-button").style.display = "block";
	document.getElementById("short-button").style.display = "none";
}
</script>

<div class="main-text" style="font-size:16px; text-align:left;">
	<h1 style="text-align:center;">Privacy Policy</h1>
	Last Updated: 11th March 2020
	<br>
	<div style="border: black 1.5pt solid; padding:3pt;" id="summary">
		Here's a summary of our Privacy Policy:
		<p>We may store your data for a few things such as analytics and to ensure that we are offering the best possible service. We will only hold your data for as long as we need it. The data we store includes names, contact details and usage data (how and when you access and/or use our website/service).</p>
		<p>We may share data with third party services such as Google Ads, to show show you adverts which support us and keep us going. We may also need share your data by law with public authorities such as the Police or a government agency.</p>
		<p>We do not knowingly store any data from anyone under the age of 13.</p>
		<p>We will always try to contact you if there are any changes to our Privacy Policy.</p>
		<p>And most importantly - WE WILL ALWAYS ENDEAVOUR TO KEEP YOUR DATA SECURE.</p>
	</div>
	<button id="full-button" onclick="full()">View Our Full Privacy Policy ↓</button>
	<button id="short-button" onclick="summary()" style="display:none;">View Our Privacy Policy Summary ↑</button>
	<div id="full-policy" style="display:none;" class="">
		<p>This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.</p>
		<p>We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy. This Privacy Policy is maintained by the Privacy Policy Generator.</p>
		<h2>Interpretation and Definitions</h2>
		<h3>Interpretation</h3>
		<p>The words of which the initial letter is capitalized have meanings defined under the following conditions.</p>
		<p>The following definitions shall have the same meaning regardless of whether they appear in singular or in the plural.</p>
		<h3>Definitions</h3>
		For the purposes of this Privacy Policy:
		<ul>
			<li>You means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
			<li>Company (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to Sprouse Websites, 9 Tennison Road, South Norwood.</li>
			<li>Affiliate means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</li>
			<li>Account means a unique account created for You to access our Service or parts of our Service.</li>
			<li>Website refers to Sprouse Websites, accessible from www.sprousewebsites.co.uk</li>
			<li>Service refers to the Website.</li>
			<li>Country refers to the United Kingdom</li>
			<li>Service Provider means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</li>
			<li>Third-party Social Media Service refers to any website or any social network website through which a User can log in or create an account to use the Service.</li>
			<li>Personal Data is any information that relates to an identified or identifiable individual.</li>
			<li>Cookies are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</li>
			<li>Usage Data refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
		</ul>

		<h2>Collecting and Using Your Personal Data</h2>
		<h3>Types of Data Colected</h3>
		<h4>Personal Data</h4>
		While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:
		<ul>
			<li>Email address</li>
			<li>First name and last name</li>
			<li>Phone number</li>
			<li>Address, State, Province, ZIP/Postal code, City</li>
			<li>Usage Data</li>
		</ul>
		<h4>Usage Data</h4>
		<p>Usage Data is collected automatically when using the Service.</p>
		<p>Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>
		<p>When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.</p>
		<p>We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.</p>

		<h4>Tracking Technologies and Cookies</h4>
		<p>We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service.</p>
		<p>You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service.</p>
		<p>Cookies can be "Persistent" or "Session" Cookies. Persistent Cookies remain on your personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You close your web browser.</p>
		We use both session and persistent Cookies for the purposes set out below:

		<table>
			<tr>
				<td style="vertical-align:top;">&#8226;</td>
				<td>
					<h5 style="margin: 0pt;">Necessary / Essential Cookies</h5>
					Type: Session Cookies
					<br>
					Administered by: Us
					<br>
					Purpose: These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features. They help to authenticate users and prevent fraudulent use of user accounts. Without these Cookies, the services that You have asked for cannot be provided, and We only use these Cookies to provide You with those services.
				</td>
			</tr>
			<tr>
				<td style="vertical-align:top;">&#8226;</td>
				<td>
					<h5 style="margin: 0pt;">Cookies Policy / Notice Acceptance Cookies</h5>
					Type: Persistent Cookies
					<br>
					Administered by: Us
					<br>
					Purpose: These Cookies identify if users have accepted the use of cookies on the Website.
				</td>
			</tr>
			<tr>
				<td style="vertical-align:top;">&#8226;</td>
				<td><h5>Functionality Cookies</h5>
					Type: Persistent Cookies
					<br>
					Administered by: Us
					<br>
					Purpose: These Cookies allow us to remember choices You make when You use the Website, such as remembering your login details or language preference. The purpose of these Cookies is to provide You with a more personal experience and to avoid You having to re-enter your preferences every time You use the Website.
				</td>
			</tr>
			<tr>
				<td style="vertical-align:top;">&#8226;</td>
				<td>
					<h5>Tracking and Performance Cookies</h5>
					Type: Persistent Cookies
					<br>
					Administered by: Third-Parties
					<br>
					Purpose: These Cookies are used to track information about traffic to the Website and how users use the Website. The information gathered via these Cookies may directly or indirectly identify you as an individual visitor. This is because the information collected is typically linked to a pseudonymous identifier associated with the device you use to access the Website. We may also use these Cookies to test new advertisements, pages, features or new functionality of the Website to see how our users react to them.
				</td>
			</tr>
			<tr>
				<td style="vertical-align:top;">&#8226;</td>
				<td>
					<h5>Targeting and Advertising Cookies</h5>
					Type: Persistent Cookies
					<br>
					Administered by: Third-Parties
					<br>
					Purpose: These Cookies track your browsing habits to enable Us to show advertising which is more likely to be of interest to You. These Cookies use information about your browsing history to group You with other users who have similar interests. Based on that information, and with Our permission, third party advertisers can place Cookies to enable them to show adverts which We think will be relevant to your interests while You are on third party websites.
				</td>
			</tr>
		</table>

		For more information about the cookies we use and your choices regarding cookies, please visit our Cookies Policy.

		<h3>Use of Your Personal Data</h3>
		The Company may use Personal Data for the following purposes:
		<ul>
			<li><b>To provide and maintain our Service</b>, including to monitor the usage of our Service.</li>
			<li><b>To manage Your Account:</b> to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.</li>
			<li><b>For the performance of a contract:</b> the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.</li>
			<li><b>To contact You</b> by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application's push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation. This may include making sure that you are happy with the product/service.</li>
			<li><b>To provide You</b> with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless You have opted not to receive such information.</li>
			<li><b>To manage Your Requests: </b>To attend and manage Your requests.</li>
		</ul>
		We may share your personal information in the following situations:
		<ul>
			<li><b>With Service Providers:</b> We may share Your personal information with Service Providers to monitor and analyze the use of our Service, to show advertisements to You to help support and maintain Our Service, to contact You, to advertise on third party websites to You after You visited our Service or for payment processing.</li>
			<li><b>For Business transfers: </b>We may share or transfer Your personal information in connection with, or during negotiations of, any merger, sale of Company assets, financing, or acquisition of all or a portion of our business to another company.</li>
			<li><b>With Affiliates: </b>We may share Your information with Our affiliates, in which case we will require those affiliates to honour this Privacy Policy. Affiliates include Our parent company and any other subsidiaries, joint venture partners or other companies that We control or that are under common control with Us.</li>
			<li><b>With Business partners:</b> We may share Your information with Our business partners to offer You certain products, services or promotions.</li>
			<li><b>With other users:</b> when You share personal information or otherwise interact in the public areas with other users, such information may be viewed by all users and may be publicly distributed outside. If You interact with other users or register through a Third-Party Social Media Service, Your contacts on the Third-Party Social Media Service may see You name, profile, pictures and description of Your activity. Similarly, other users will be able to view descriptions of Your activity, communicate with You and view Your profile.</li>
		</ul>

		<h3>Retention of Your Personal Data</h3>
		<p>The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.</p>
		<p>The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of Our Service, or We are legally obligated to retain this data for longer time periods.</p>
		<h3>Transfer of Your Personal Data</h3>
		<p>Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from Your jurisdiction.</p>
		<p>Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer.</p>
		<p>The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of Your data and other personal information.</p>

		<h3>Disclosure of Your Personal Data</h3>
		<h4>Business Transactions</h4>
		If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.
		<h4>Law enforcement</h4>
		Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).
		<h4>Other legal requirements</h4>
		The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:
		<ul>
			<li>Comply with a legal obligation</li>
			<li>Protect and defend the rights or property of the Company</li>
			<li>Prevent or investigate possible wrongdoing in connection with the Service</li>
			<li>Protect the personal safety of Users of the Service or the public</li>
			<li>Protect against legal liability</li>
		</ul>
		<h3>Security of Your Personal Data</h3>
		The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.

		<h2>Detailed Information on the Processing of Your Personal Data</h2>
		<p>Service Providers have access to Your Personal Data only to perform their tasks on Our behalf and are obligated not to disclose or use it for any other purpose.</p>
		<h3>Analytics</h3>
		We may use third-party Service providers to monitor and analyze the use of our Service.
		<h4>Google Analytics</h4>
		Google Analytics is a web analytics service. Read the Privacy Policy for Google Analytics here: <a href="https://policies.google.com/privacy">https://policies.google.com/privacy</a>
		<h4>Clicky</h4>
		Clicky is a web analytics service. Read the Privacy Policy for Clicky here: <a href="https://clicky.com/terms/privacy" class="hover-u">https://clicky.com/terms/privacy</a>
		<h3>Advertising</h3>
		We may use Service providers to show advertisements to You to help support and maintain Our Service.
		<h4>Google Ads</h4>
		Google Ads is an advertising service provided by Google LLC.
		<br>
		You can opt-out from Google Ads by following the instructions on the Google Ads Opt-out page: https://support.google.com/ads/answer/2662922?hl=en-GB
		<br>
		For more information about Google Ads, please visit their Privacy Policy: https://policies.google.com/privacy
		<h2>Children's Privacy</h2>
		<p>Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information from Our servers.</p>
		<p>We also may limit how We collect, use, and store some of the information of Users between 13 and 18 years old. In some cases, this means We will be unable to provide certain functionality of the Service to these users.</p>
		<p>If We need to rely on consent as a legal basis for processing Your information and Your country requires consent from a parent, We may require Your parent's consent before We collect and use that information.</p>
		<h2>Links to Other Websites</h2>
		<p>Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit.</p>
		<p>We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.</p>
		<h1>Changes to this Privacy Policy</h1>
		<p>We may update our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.</p>
		<p>We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the "Last updated" date at the top of this Privacy Policy.</p>
		<p>You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</p>
		<h2>Contact Us</h2>
		If you have any questions about this Privacy Policy, You can contact us:
		<ul>
			<li>By email: joel@sprousewebsites.co.uk</li>
		</ul>
		<button id="short-button" onclick="summary()" style="display:none;">View Our Privacy Policy Summary ↑</button>
	</div>

</div>

<?php
include 'includes/footer.php';
?>
